//@ known-failure
fn main() {
    panic!("O no");
}
